version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run uvicorn app.main:app --host 0.0.0.0 --reload
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    env_file:
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: