CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    country_code VARCHAR(10) NOT NULL,
    cellphone VARCHAR(100) UNIQUE NOT NULL,
    name TEXT NOT NULL,
    email TEXT NOT NULL
);

CREATE TYPE user_feature_type AS ENUM ('AI_NODE', 'META_ADS', 'HUBSPOT_SIDE_PANEL', 'HUBSPOT_CUSTOM_EVENTS', 'DYNAMIC_WHATSAPP_FLOWS');

CREATE TABLE IF NOT EXISTS user_features (
    id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    user_id uuid NOT NULL REFERENCES users(id),
    type user_feature_type NOT NULL
);